[sensors] Launch `vectornav` in `bringup.launch.py`
RoboJackets/urc-software pull request #229
Opened 2024-11-01 20:44 UTC by mazam32

# Description
This PR does the following:
- Changed the bringup launch file so that it launches vectornav launch file implicitly
- Provides a new file in documents folder to fix issues with laptops with access denied issues.

2024-11-01 21:09 UTC, davidcalderon03 requested changes
Please remove the build, install, and log files from this PR. You need to build the repo in rover-colon, not src

2024-11-01 21:45 UTC, davidcalderon03 approved these changes
LGTM!

2024-11-03 19:48 UTC, yambati03 requested changes
The changes to `bringup.launch.py` look good, but had a few comments about the other checked in code. Also, we'll likely want a way to quickly zero the IMU (not sure if the `vectornav` already comes with a service to do this). I'd also add some instructions for calibrating the IMU and setting the correct magnetic declination.

2024-11-03 19:48 UTC, yambati03 commented on urc_localization/src/ned_to_enu.cpp
Is this file supposed to be here? It is empty.

2024-11-03 19:48 UTC, yambati03 commented on urc_platform/src/imu_parser.cpp
I don't think we need this IMU parser node anymore. There should be an option in the config file for the `vectornav` package that will automatically publish a ROS 2 `sensor_msgs/Imu` message.

2024-11-24 21:48 UTC, merged