Feat/multiclass node
RoboJackets/urc-software pull request #51
Opened 2022-07-26 16:17 UTC by a-stickan

# Description

This PR does the following:
- Adds a node for multiclass segmentation
- Adds a launch file for the node

# Testing steps (If relevant)
1. `colcon build && colcon test && colcon test-result --verbose`
2. `. install/setup.bash`
3. `ros2 launch urc_perception multiclass_segmentation.launch.py`

Expectation: Node starts up, but fails due to `No such file or directory: 'Allan/Please/Add/Details'`

# Self Checklist
- [x] I have formatted my code using `ament_uncrustify --reformat`
- [x] I have tested that the new behavior works

2022-07-27 23:05 UTC, VAM7686 requested changes
Nice job! Just have some minor questions.

2022-07-27 23:05 UTC, VAM7686 commented on urc_gazebo/launch/simulation.launch.py
>      scan_to_pointcloud = Node(
Do we actually need the scan to pointcloud node in simulation?

2022-07-27 23:05 UTC, VAM7686 commented on urc_navigation/config/ekf_localization_node_params.yaml
> +    odom1_config: [ true, true, false,
Will we be performing 3d localization? If so it is probably a good idea to configure the GPS parameters accordingly. Similar to [this](https://github.com/RoboJackets/igvc-software/blob/c4de30fc741c9fb3d0923596bb2263d947eec3dd/igvc_navigation/config/ekf_localization_node_params.yaml) configuration perhaps?

2022-07-27 23:23 UTC, a-stickan commented on urc_gazebo/launch/simulation.launch.py
>      scan_to_pointcloud = Node(
I don't think we do, removing before I merge this branch in

2022-07-27 23:27 UTC, a-stickan commented on urc_navigation/config/ekf_localization_node_params.yaml
> +    odom1_config: [ true, true, false,
We will be performing 3D localization, must have just set the param to true by accident. Fixed in most recent commit

2022-07-28 00:26 UTC, VAM7686 approved these changes
looks good to me!

2022-07-28 00:58 UTC, merged