Implement UDP communication
RoboJackets/urc-software pull request #88
Opened 2022-10-20 04:10 UTC by AR2100

# Description
This PR adds basic UDP functionality.

This PR does the following
- The Teensy can send encoder estimates as a Nanopb message to the main computer
- Tested with `feat/ci_pipline` branch in `urc-firmware` repo

Fixes #59 

# Testing Steps
1. Build and deploy firmware code on `feat/ci_pipline`
2. `colcon build` the `feat/udp_communication` branch
3. launch `chassis_controller` node

Expectation:  encoder messages being echoed on `/encoders`

# Self Checklist
- [ ] I have formatted my code using `ament_uncrustify --reformat`
- [ ] I have tested that the new behavior works

2022-10-23 00:50 UTC, a-stickan requested changes

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/include/chassis_controller.hpp
> +class ChassisControllerDriver
This should probably be a nested class

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/include/chassis_controller.hpp
> +class ChassisControllerDriver
Probably make this an inner class, generally restructure

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/chassis_controller_wrapper.cpp
> +    std::chrono::duration<double>(1.0 / publish_encoder_ticks_frequency_),
Why is this templated to a double?

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/chassis_controller_wrapper.cpp
> +    std::bind(&ChassisControllerWrapper::publishEncoderTicks, this));
Please use lambdas instead of bind if possible

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/chassis_controller_wrapper.cpp
> +    RCLCPP_ERROR(this->get_logger(), "Decoding Failed");
Probably make this warning instead, doesn't warrant shutting everything down imo

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/main.cpp
> +int main(int argc, char ** argv)
Why are you using single-threaded executors? Do you really need this for the node to function

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +#define NODE_MAIN_LOGGER_NAME "urc_platform_MotorController"
No macros please

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  // // Battery variables
Remove legacy code

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  // // PID variables
Remove legacy code

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  // mc_updater_->setHardwareID("Motor Controller");
Remove ALL legacy code, don't comment it out

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  int i = 0;
Scuffed

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +    encoder_msg.right_velocity = -1 * (i++);
Please explain why this is being incremented, probably refactor

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +    encoder_msg.left_velocity = (double)bytes_read;
Use static casts when applicable

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  // std_msgs::msg::Float64 battery_msg;
Remove legacy code

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +  // enabled_msg.data = response.estop;
Remove legacy code

2022-10-23 00:50 UTC, a-stickan commented on urc_platform/src/motor_controller.cpp
> +bool MotorController::poll()
???

2022-10-23 00:50 UTC, a-stickan commented on urc_util/src/ethernet_socket.cpp
> +  char test[] = "hello back";
No tests in live code

2022-10-30 22:07 UTC, avayedawadi commented
- Delete main.cpp because launch files handle everything
- ChassisControllerDriver should be a private class inside of ChassisControllerWrapper
    - Then just rename to ChassisController
    - chassis_controller.hpp
- Why pass as parameters when you can just use the variables straight up
    - I’m a bit confused on this
    - Follow Joystick for how to pass parameters and in general for node design
- What we don’t need, get rid of (motor_controller.cpp stuff?)
- Use lambda instead of bind
- Don’t have an arbitrary size for buffer size and use a constant from the header file instead (gives better adjustment)
- urc_gazebo is the best launch file
    - Launch files that launch

2022-11-17 01:53 UTC, a-stickan approved these changes

2022-11-20 21:36 UTC, merged