Docker Drone Installation Instructions
RoboJackets/urc-software pull request #90
Opened 2022-10-24 04:16 UTC by AR2100

# Description
This PR does the following:
- Update docker install instructions 
- Fix 

# Testing Steps (if relevant)
1. Follow docker installation instructions using manual build method
2. `colcon build` urc drone and urc rover
3. check that gui works (try `gazebo` and `rviz2`

Expectation: everything works

# Self Checklist
- [ ] I have formatted my code using `ament_uncrustify --reformat`
- [ ] I have tested that the new behavior works

2022-10-24 04:35 UTC, AR2100 commented
Once this is approved, I'll update Dockerhub repo

2022-12-25 18:31 UTC, a-stickan requested changes
Should be good assuming that one line is changed

2022-12-25 18:31 UTC, a-stickan commented on docker_gui/Dockerfile
> -RUN apt-get update --fix-missing
Don't remove this, best practice imo

2023-05-01 21:39 UTC, a-stickan commented
Stale PR, closing

2023-05-01 21:39 UTC, closed without merging